# This YAML (.yml) gilab-ci file is used by GitLab pages to deploy the code to the servers. 
# For more information on deploying to GitLab Pages consult the following resources:
# https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ci_cd_template.html
# https://cli.vuejs.org/guide/deployment.html#gitlab-pages

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - npm clean --force
    - npm cache verify
    - npm ci
    - npm run build
    # GitLab Pages hooks on the public folder
    - mv public ./public-vue 
    # rename the dist folder (result of npm run build)
    - mv dist ./public 
    # optionally, you can activate gzip support wih the following line:
    - find ./public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - development

# Deploys non-master branches to surge
# https://medium.com/jubianchi-fr/preview-your-website-with-gitlab-ci-and-surge-5b861d7c9a3a
preview:
  stage: deploy
  script:
    - npm install
    - npm run surge
    - SLUG=$(echo ${CI_COMMIT_BRANCH} | sed 's/[^a-zA-Z0-9\-_]/-/g ; s/-\+/-/g')
    - node_modules/.bin/surge list
    - node_modules/.bin/surge public evilscaught-beta-${SLUG}.surge.sh
  except:
    - master