# This YAML (.yml) gilab-ci file is used by GitLab pages to deploy the code to the servers. 
# For more information on deploying to GitLab Pages consult the following resources:
# https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ci_cd_template.html
# https://cli.vuejs.org/guide/deployment.html#gitlab-pages

# Deploys non-master branches to surge
# https://medium.com/jubianchi-fr/preview-your-website-with-gitlab-ci-and-surge-5b861d7c9a3a
preview:
  image: node:latest
  stage: deploy
  script:
    - npm install
    - npm run surge
    - SLUG=$(echo ${CI_COMMIT_BRANCH} | sed 's/[^a-zA-Z0-9\-_]/-/g ; s/-\+/-/g')
    - node_modules/.bin/surge list
    - node_modules/.bin/surge public evilscaught-beta-${SLUG}.surge.sh
  except:
    - master