# This YAML (.yml) gilab-ci file is used by GitLab pages to deploy the code to the servers. 
# For more information on deploying to GitLab Pages consult the following resources:
# https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ci_cd_template.html
# https://cli.vuejs.org/guide/deployment.html#gitlab-pages

# The job must be named pages
pages: 
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    # optionally, you can activate gzip support wih the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master